version: '3.7'

services:

  htmx-server:
    build:
      context: .
      dockerfile: ./build/fastapi/Dockerfile
      target: dev
    container_name: htmx
    environment:
      PB_HOST: ${PB_HOST}
      PB_ADMIN_USERNAME: ${PB_ADMIN_USERNAME}
      PB_ADMIN_PASSWORD: ${PB_ADMIN_PASSWORD}
    ports:
      - 8000:80
    volumes:
      - ./src/app:/app/app

  pocketbase:
    build:
      context: .
      dockerfile: ./build/pocketbase/Dockerfile
    container_name: pocketbase
    volumes:
      - ./src/pb/pb_migrations:/app/data/pb_migrations
      - ./src/pb/pb_public:/app/data/pb_public
    ports:
      - "8090:8090"
