version: '3.7'

services:

  htmx-server:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: production
    container_name: htmx
    ports:
      - 8000:80

  pocketbase:
    build:
      context: .
      dockerfile: ./build/pocketbase/Dockerfile
    container_name: pocketbase
    volumes:
      - ./src/pb:/app/data
    ports:
      - "8090:8090"